site_name: SiteWebProjetAlbumPhotoSTM32F7
nav: 
  - Accueil: index.md
  - Documentation Album Photo: documentation.md
  - Pr√©sentation SDMMC: presentation.md
theme: readthedocs
site_url: https://Marsuboubou.github.io
site_dir: public
